travis:
  secure:
    BINSTAR_TOKEN: mz+mRhHgXEGPbBc3/pbMm5YwpYgKZafeqgMdwXdJBJ7a0ao/ebzvAd/ynpwjYNemYDiXb4NK5GNMQjzbWQSeYa6C9P7rhpNFlzaBICYYaGdcy88vKlzrarbVZ3fbEVoW/kdUHPke7YTOfKMfaKsUCNiyKlbl++oxf1vakmX3vlZHw4kRaIHzw/J34tdEssFEgoA3orVNZtoKBH4ArxnRYshaG8yweVzCBaOlv3gMy7D5xgvw0HG2iu1flpGVCehulq1jSkmbA6Jk9Mm0Qp89bDlbXCkPpF5YAZUZKwdgspXKEKDDneEXuvZVgwuB/tXh9tMpOmMpzp3Kk/TMHfiuw15zSrOz88XuPYP0eVwA0zXBm5FP++gbpM+4A7dyXuTr+TrRSOKjJh5GFSiyoaxi29vC4bNXpRO1iYD2cvGHr9sPRGJQoY4o5ZUDJjGI71AdV6xlq1l5IOm5lrrSHa8J/8dRSw2793pobEU/0ZL6JEwGuRtNBrfU+4RXOqjvcpYCcwcDFvhdCmX33j95OgpE510aV24XwQwOKvTx2oz7Q+ayaPV6VQ+E/z1DZKuiAeaPzzszGhiCLHocHZMIjWjqExEuAsj0FJ4VhIiYw/yK7UXaodpTzrmjj6AxJDW5654/oJotTbA4JB6id8xGWyl2PMLdPcmsoQ0L/9wEoKa2fJQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
